import type { Metadata } from 'next'
import './globals.css'
import { cn } from '@/utils/lib/tailwind'
import Header from '@/components/layout/header'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    'min-h-screen bg-foreground font-sans antialiased'
                )}
            >
                <Header />
                <main>{children}</main>
            </body>
        </html>
    )
}
